<a href="https://colab.research.google.com/github/Aquamarine278/Neural-Network-Challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head(15)

Age Attrition     BusinessTravel              Department  \
0    41       Yes      Travel_Rarely                   Sales   
1    49        No  Travel_Frequently  Research & Development   
2    37       Yes      Travel_Rarely  Research & Development   
3    33        No  Travel_Frequently  Research & Development   
4    27        No      Travel_Rarely  Research & Development   
5    32        No  Travel_Frequently  Research & Development   
6    59        No      Travel_Rarely  Research & Development   
7    30        No      Travel_Rarely  Research & Development   
8    38        No  Travel_Frequently  Research & Development   
9    36        No      Travel_Rarely  Research & Development   
10   35        No      Travel_Rarely  Research & Development   
11   29        No      Travel_Rarely  Research & Development   
12   31        No      Travel_Rarely  Research & Development   
13   34        No      Travel_Rarely  Research & Development   
14   28       Yes      Travel_Rarely  Research & Development   

    DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                  1          2  Life Sciences                        2   
1                  8          1  Life Sciences                        3   
2                  2          2          Other                        4   
3                  3          4  Life Sciences                        4   
4                  2          1        Medical                        1   
5                  2          2  Life Sciences                        4   
6                  3          3        Medical                        3   
7                 24          1  Life Sciences                        4   
8                 23          3  Life Sciences                        4   
9                 27          3        Medical                        3   
10                16          3        Medical                        1   
11                15          2  Life Sciences                        4   
12                26          1  Life Sciences                        1   
13                19          2        Medical                        2   
14                24          3  Life Sciences                        3   

    HourlyRate  JobInvolvement  ...  PerformanceRating  \
0           94               3  ...                  3   
1           61               2  ...                  4   
2           92               2  ...                  3   
3           56               3  ...                  3   
4           40               3  ...                  3   
5           79               3  ...                  3   
6           81               4  ...                  4   
7           67               3  ...                  4   
8           44               2  ...                  4   
9           94               3  ...                  3   
10          84               4  ...                  3   
11          49               2  ...                  3   
12          31               3  ...                  3   
13          93               3  ...                  3   
14          50               2  ...                  3   

   RelationshipSatisfaction  StockOptionLevel TotalWorkingYears  \
0                         1                 0                 8   
1                         4                 1                10   
2                         2                 0                 7   
3                         3                 0                 8   
4                         4                 1                 6   
5                         3                 0                 8   
6                         1                 3                12   
7                         2                 1                 1   
8                         2                 0                10   
9                         2                 2                17   
10                        3                 1                 6   
11                        4                 0

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [34]:
display(attrition_df['Attrition'].value_counts())
display(attrition_df['Department'].value_counts())

Attrition
No     1233
Yes     237
Name: count, dtype: int64

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [4]:
# let look at the dataset a little more in depth
attrition_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64 
 5   Education                 1470 non-null   int64 
 6   EducationField            1470 non-null   object
 7   EnvironmentSatisfaction   1470 non-null   int64 
 8   HourlyRate                1470 non-null   int64 
 9   JobInvolvement            1470 non-null   int64 
 10  JobLevel                  1470 non-null   int64 
 11  JobRole                   1470 non-null   object
 12  JobSatisfaction           1470 non-null   int64 
 13  MaritalStatus             1470 non-null   object
 14  NumCompaniesWorked      

In [5]:
# Create a list of at least 10 column names to use as X data
feature_columns = ['Education', 'Age',  'DistanceFromHome',
                   'EnvironmentSatisfaction', 'HourlyRate',
                   'JobInvolvement', 'JobLevel',  'JobSatisfaction', 'OverTime',
                   'PerformanceRating', 'StockOptionLevel',
                   'WorkLifeBalance','YearsAtCompany', 'YearsSinceLastPromotion'
                   ]


# Create X_df using your selected columns
X_df = attrition_df[feature_columns]


# Show the data types for X_df
print(X_df.dtypes)


Education                   int64
Age                         int64
DistanceFromHome            int64
EnvironmentSatisfaction     int64
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobSatisfaction             int64
OverTime                   object
PerformanceRating           int64
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
dtype: object


In [6]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=42)


In [7]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

print(X_df['OverTime'].value_counts())

OverTime
No     1054
Yes     416
Name: count, dtype: int64


In [8]:
# use OneHotEncoder to encode the 'Overtime' column
# drop one of the columns to avoid multicollinearity
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop= 'first')
ohe.set_output(transform="pandas")
overtime_train_enc = ohe.fit_transform(X_train[['OverTime']])
overtime_test_enc = ohe.transform(X_test[['OverTime']])


In [9]:
# add the encoded train overtime column to the X_train and drop the original 'Overtime' column
X_train = pd.concat([X_train, overtime_train_enc], axis=1)
X_train.drop(columns=['OverTime'], inplace=True)
# add the encoded test overtime column to the X_test and drop the original 'Overtime' column
X_test = pd.concat([X_test, overtime_test_enc], axis=1)
X_test.drop(columns=['OverTime'], inplace=True)


Education  Age  DistanceFromHome  EnvironmentSatisfaction  HourlyRate  \
1343          3   29                 7                        4          59   
1121          4   36                 1                        2          73   
1048          3   34                 3                        4          81   
1393          3   27                 9                        4          44   
527           3   32                10                        4          55   
...         ...  ...               ...                      ...         ...   
1130          3   35                28                        2          46   
1294          3   41                 5                        2          85   
860           4   22                 3                        3          48   
1459          2   29                13                        4          46   
1126          3   50                 9                        3          59   

      JobInvolvement  JobLevel  JobSatisfaction  PerformanceRating  \
1343               3         1                1                  3   
1121               3         2                3                  3   
1048               1         2                1                  3   
1393               3         2                4                  3   
527                3         2                4                  3   
...              ...       ...              ...                ...   
1130               4         2                3                  3   
1294               4         2                2                  3   
860                2         1                4                  3   
1459               2         2                2                  3   
1126               3         5                3                  3   

      StockOptionLevel  WorkLifeBalance  YearsAtCompany  \
1343                 0                3               3   
1121                 0                3               1   
1048                 0                3              13   
1393                 0                3               7   
527                  0                2              10   
...                ...              ...             ...   
1130                 2                2              10   
1294                 0                1               3   
860                  1                3               0   
1459                 1                3               4   
1126                 1                3               1   

      YearsSinceLastPromotion  OverTime_Yes  
1343                        1           0.0  
1121                        0           0.0  
1048                        3           0.0  
1393                        0           0.0  
527                         0           0.0  
...                       ...           ...  
1130                        6           0.0  
1294                        1           0.0  
860                         0           1.0  
1459                        0           1.0  
1126                        0           1.0  

[1102 rows x 14 columns]

In [10]:
# Create a StandardScaler
scaler =  StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [11]:
# Create a OneHotEncoder for the Department column
dept_ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder to the training data
dept_ohe.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
department_train_enc = dept_ohe.transform(y_train[['Department']])
department_test_enc = dept_ohe.transform(y_test[['Department']])

print(department_test_enc)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [14]:
# Create a OneHotEncoder for the Attrition column
att_ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder to the training data
att_ohe.fit(y_train[['Attrition']])
# Create two new variables by applying the encoder
# to the training and testing data
attrition_train_enc = att_ohe.transform(y_train[['Attrition']])
attrition_test_enc = att_ohe.transform(y_test[['Attrition']])

print(attrition_train_enc)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [18]:
X_train_scaled.shape[1]

14

In [21]:
# Find the number of columns in the X training data
print(X_train_scaled.shape[1])

# Create the input layer
input_layer = layers.Input(shape= (X_train_scaled.shape[1],), name= 'input features')

# Create at least two shared layers
shared_layer1 = layers.Dense(units= 64, activation= 'relu', name= 'shared_layer1')(input_layer)
shared_layer2 = layers.Dense(units= 128, activation= 'relu', name= 'shared_layer2')(shared_layer1)

14


In [22]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden = layers.Dense(units= 32, activation= 'relu', name= 'department_hidden')(shared_layer2)

# Create the output layer
department_output = layers.Dense(units= 3, activation= 'softmax', name= 'department_output')(department_hidden)


In [23]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(units= 32, activation= 'relu', name= 'attrition_hidden')(shared_layer2)

# Create the output layer
attrition_output = layers.Dense(units= 2, activation= 'sigmoid', name= 'attrition_output')(attrition_hidden)


In [24]:
# Create the model
model = Model(inputs= input_layer, outputs= [department_output, attrition_output])

# Compile the model
model.compile(optimizer = 'adam',
              loss = {'department_output' : 'categorical_crossentropy', 'attrition_output': 'binary_crossentropy'},
              metrics = {'department_output' : 'accuracy', 'attrition_output': 'accuracy'})

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input features            │ (None, 14)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared_layer1 (Dense)     │ (None, 64)             │            960 │ input features[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared_layer2 (Dense)     │ (None, 128)            │          8,320 │ shared_layer1[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_hidden (Dense) │ (None, 32)             │          4,128 │ shared_layer2[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_hidden (Dense)  │ (None, 32)             │          4,128 │ shared_layer2[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             99 │ department_hidden[0][… │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             66 │ attrition_hidden[0][0] │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 17,701 (69.14 KB)

 Trainable params: 17,701 (69.14 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
# Train the model
model.fit(X_train_scaled,
          {'department_output': department_train_enc, 'attrition_output': attrition_train_enc},
          epochs= 100,
          batch_size= 32,
          validation_data= (X_test_scaled, {'department_output': department_test_enc, 'attrition_output': attrition_test_enc}))


Epoch 1/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - attrition_output_accuracy: 0.6392 - attrition_output_loss: 0.6269 - department_output_accuracy: 0.5681 - department_output_loss: 0.9300 - loss: 1.5568 - val_attrition_output_accuracy: 0.8696 - val_attrition_output_loss: 0.3947 - val_department_output_accuracy: 0.6522 - val_department_output_loss: 0.8018 - val_loss: 1.1840
Epoch 2/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - attrition_output_accuracy: 0.8160 - attrition_output_loss: 0.4491 - department_output_accuracy: 0.6624 - department_output_loss: 0.7739 - loss: 1.2229 - val_attrition_output_accuracy: 0.8696 - val_attrition_output_loss: 0.3672 - val_department_output_accuracy: 0.6522 - val_department_output_loss: 0.7935 - val_loss: 1.1479
Epoch 3/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8366 - attrition_output_loss: 0.3955 - department_output_accuracy: 0.6509 - department_output_loss: 0.7505 - loss: 1.1462 - val_attrition_output_accuracy: 0.8804 -

In [28]:
# Evaluate the model with the testing data
results = model.evaluate(X_test_scaled, {'department_output': department_test_enc, 'attrition_output': attrition_test_enc})
print(results)

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8432 - attrition_output_loss: 0.9673 - department_output_accuracy: 0.5191 - department_output_loss: 3.4933 - loss: 4.4514 
[4.191570281982422, 3.237469434738159, 1.0142096281051636, 0.8505434989929199, 0.5380434989929199]


In [31]:
# Print the accuracy for both department and attrition
print(f'Department Accuracy: {results[4]}')
print(f'Attrition Accuracy: {results[3]}')

Department Accuracy: 0.5380434989929199
Attrition Accuracy: 0.8505434989929199


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Balanced accuracy would be better because there was class imbalance in this in the departments and attritions column.
2. Softmax for multi-class classification and sigmoid for binary classification.
3. Use oversampling or undersampling to balance classes for training, increase number of neurons in hidden layers, and increasing number of layers.
